-- ═══════════════════════════════════════════════════════════════════════════
-- Elyara — Seed Products
-- Run this AFTER schema.sql in Supabase SQL Editor.
-- Inserts all 11 products from the original data.ts catalog.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO products (name, style_no, price, original_price, category, collection, description, images, is_bestseller, is_new, is_customizable, status, sizes, colors)
VALUES
  (
    'Mira',
    '001',
    5999,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A brocade peplum top in iridescent blue-gold fabric paired with fluid navy trousers. The structured flare and sweetheart neckline create a silhouette that commands attention. Fully customisable to your measurements.',
    ARRAY['/assets/cat1.jpg', '/assets/cat2.jpg'],
    true,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Blue-Gold Brocade']
  ),
  (
    'Paro',
    '002',
    4999,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A metallic gold corset top with dramatic draped black skirt. Lace-up back detailing adds an edge to this evening-ready ensemble. Each piece tailored to your exact measurements.',
    ARRAY['/assets/cat3.jpg', '/assets/cat4.jpg'],
    true,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Gold & Black']
  ),
  (
    'Inaya',
    '003',
    6999,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A delicate 3D floral net cape over a structured silver-grey crop top and wide-leg trousers. Intricate hand-crafted floral appliqués make this a true statement piece.',
    ARRAY['/assets/cat5.jpg', '/assets/cat6.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Silver Grey']
  ),
  (
    'Alaya',
    '004',
    4999,
    NULL,
    'dresses',
    'Signature Edit',
    'A floor-sweeping floral maxi dress in rich pink georgette. Features a sweetheart neckline and flowing A-line silhouette — effortlessly romantic and fully customisable in length and fit.',
    ARRAY['/assets/cat7.jpg', '/assets/cat8.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Blush Pink Floral']
  ),
  (
    'Chaand Corset',
    '005',
    2599,
    NULL,
    'tops',
    'Signature Edit',
    'A structured metallic bronze corset with lace-up back detailing. Versatile enough to style with trousers, skirts, or draped sarees. A wardrobe-defining staple.',
    ARRAY['/assets/hero_files/main1.jpg', '/assets/hero_files/Hero1.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Metallic Bronze']
  ),
  (
    'Noor',
    '006',
    4599,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A geometric-print halter top with draped black trousers. A modern Indian fusion silhouette that effortlessly blends heritage textile craft with contemporary structure.',
    ARRAY['/assets/hero_files/Hero2.jpg', '/assets/hero_files/main2.jpg'],
    true,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Black & Gold Print']
  ),
  (
    'Aira',
    '007',
    3999,
    NULL,
    'coord-sets',
    'Signature Edit',
    'An ikat-print fitted bodice paired with a fluid black maxi skirt. The V-neckline and sleeveless cut create a clean, modern silhouette rooted in Indian craft traditions.',
    ARRAY['/assets/hero_files/elyara.jpg', '/assets/cat1.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Ikat Print & Black']
  ),
  (
    'Roselle',
    '008',
    4499,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A three-piece ajrakh-print coord set — cold-shoulder top, wide-leg pants, and a matching dupatta. A celebration of block-print heritage reimagined for the modern woman.',
    ARRAY['/assets/cat2.jpg', '/assets/cat3.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Ajrakh Brown & Black']
  ),
  (
    'Elora',
    '009',
    4899,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A structured black satin blazer paired with an ikat-print draped skirt. Clean tailoring meets artisan textile in this versatile fusion ensemble. New arrival.',
    ARRAY['/assets/cat4.jpg', '/assets/cat5.jpg'],
    false,
    true,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Black & Gold Ikat']
  ),
  (
    'Piya',
    '010',
    4899,
    NULL,
    'coord-sets',
    'Signature Edit',
    'Our signature best-seller. An ajrakh-print corset top with ruffled sleeves and a dramatic draped black skirt. Worn by customers at weddings, parties, and editorial shoots across India.',
    ARRAY['/assets/cat6.jpg', '/assets/cat7.jpg'],
    true,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Ajrakh Print & Black']
  ),
  (
    'Ziva',
    '011',
    4499,
    NULL,
    'coord-sets',
    'Signature Edit',
    'A sleek black tank top with an ikat-print maxi skirt and matching neck scarf. A sophisticated monochrome-meets-print combination for effortless elegance.',
    ARRAY['/assets/cat8.jpg', '/assets/cat1.jpg'],
    false,
    false,
    true,
    'available',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    ARRAY['Black & White Ikat']
  );
